### ISSUE TITLE
Language=NULL after import, causing AdminUI crash

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#67]
Hi Valdis,

Using DbLocalizatoinProvider 5.7.5.
Yesterday we got a problem in production that after a JSON import of only a few updated entries there appeared many entries in LocalizationResourceTranslation table with Language NULL (and not for the updated entries, it is very strange). Myself I have only seen the output, so I cannot describe the steps to reproduce.
The Language=NULL entries then caused an exception in AdminUI (see at the end), so that stopped working.
Fixed it with correcting the database (in this case the entries with Language=NULL were unwanted updates, translations were there even in the fallback language). I could not reproduce the issue on my developer machine even with the same import file (but different database sadly). There were no nulls in the json import file, looked correct. So no clue how this could happen, but maybe you want to take a look at this in the code what could cause this.

With our architect we were wondering why is actually the Language column nullable, then we went through the schema and identified some suspicious marks in the database - you might want to consider to change some in a next version, so database integrity will be ensured and the database cannot get corrupted. Take this as a friendly review of the database, feel free to pick up any elemnts or ignore completely :-)

Please note that we do not know your code, it is all based only on looking at the schema alone, we might be completely off.

Table LocalizationResources:
	1. IsModified column: this could be NOT NULL, it seems NULL has no special meaning here
	2. IsHidden: this could be NOT NULL as well, I noticed that after JSON import it gets a NULL value, but I am not sure if that has any different to false

Table LocalizationResourceTranslations:
	3. ResourceId: this column could have a foreign key to LocalizationResources.Id
	4. LocalizationResource_Id: I am not sure what this column is, in our database it is always NULL, maybe it could be removed?
	5. Adding a unique constraint on ResourceId, Language to ensure that there are no duplicates getting into the database (every now and then, duplicates get in the database for us)
	6. Language: this should be definitely NOT NULL, see above :-)
	7. ModifiedDate column would be useful, similar to LocalizationResources for analysis

I think implementing these changes would also help to fight against possible issues corrupting the database.
I also understand changing some columns might break compatibility.

I also noticed that if the JSON import updates resources where FromCode was 1, after the import it is 0. But does not seem to cause any problem, I mention it because it might not be the intention.

Sorry for the huge list, please understand I just want to make the project better, this is just a collection of suggestions. Keep up the good work!

Exception in AdminUI if Language is NULL:
`
2020-04-21 15:35:27,799;[436];ERROR;EPiServer.Global;Unhandled exception in ASP.NET
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: name
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at DbLocalizationProvider.AdminUI.LocalizationResourcesController.<>c__DisplayClass20_0.<GetAllResources>b__1(LocalizationResourceTranslation t)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DbLocalizationProvider.AdminUI.LocalizationResourcesController.GetAllResources()
   at DbLocalizationProvider.AdminUI.LocalizationResourcesController.PrepareViewModel(Boolean showMenu)
   at DbLocalizationProvider.AdminUI.LocalizationResourcesController.Main()
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_0.<InvokeActionMethodWithFilters>b__0()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   at System.Web.Mvc.Controller.ExecuteCore()
   at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)
   at System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext)
   at EPiServer.Shell.Web.Mvc.ModuleMvcHandler.ProcessController(IController controller)
   at EPiServer.Shell.Web.Mvc.ModuleMvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: name
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at DbLocalizationProvider.AdminUI.LocalizationResourcesController.<>c__DisplayClass20_0.<GetAllResources>b__1(LocalizationResourceTranslation t)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DbLocalizationProvider.AdminUI.LocalizationResourcesController.GetAllResources()
   at DbLocalizationProvider.AdminUI.LocalizationResourcesController.PrepareViewModel(Boolean showMenu)
   at DbLocalizationProvider.AdminUI.LocalizationResourcesController.Main()
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_0.<InvokeActionMethodWithFilters>b__0()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   at System.Web.Mvc.Controller.ExecuteCore()
   at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)
   at System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext)
   at EPiServer.Shell.Web.Mvc.ModuleMvcHandler.ProcessController(IController controller)
   at EPiServer.Shell.Web.Mvc.ModuleMvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
`

Regards,
Zsolt

**Comment by valdisiljuconoks** [comment]
Thanks for detailed description. I'll take a look at this within v6.1 dev (which is happening now)

**Comment by valdisiljuconoks** [comment]
All makes sense. Think this is good timing when in v6.x EF has been dropped - I can control schema more easily and will add proper scripts to make sure schema is correct.

**Comment by valdisiljuconoks** [comment]
https://github.com/valdisiljuconoks/LocalizationProvider/issues/182

**Comment by valdisiljuconoks** [comment]
https://github.com/valdisiljuconoks/LocalizationProvider/issues/183

**Comment by valdisiljuconoks** [comment]
Regarding `FromCode` set to 0 - could not repro in 6.x version

**Comment by nzsb** [comment]
Excellent, thanks for the quick response!
